lms_alimsonline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_auth.urls')),
]

user_auth/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'user_auth'

urlpatterns = [
    path('', views.home, name='home'),
    path('user_auth/register/', views.register, name="register"),
    path('user_auth/teacher-reg/', views.teacher_reg, name='teacherReg'),
    path('user_auth/signin/', views.signin, name="signin"),
    # path('studentSignup/', views.student_signup, name="studentSignup"),
]

user_auth/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add any additional fields you want for the user profile

user_auth/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.models import User, auth

from django.contrib import messages

# Create your views here.
from django.contrib.auth.forms import UserCreationForm


def home(request):
    return render(request, 'user_auth/index.html')


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        email = request.POST['email']
        username = email  # set username as email
        password = request.POST['password']

        # Check if username or email already exists
        if User.objects.filter(username=email).exists() or User.objects.filter(email=email).exists():
            messages.error(request, 'A user with this email already exists.', extra_tags='danger')
            return render(request, 'user_auth/register.html')

        # Create the new user
        user = User.objects.create_user(username=username, first_name=first_name, email=email, password=password)
        # user.save()
        messages.success(request, 'Your account has been created! You can now log in.')
        return render(request, 'user_auth/login.html')
        # print("user created")
        # return redirect('/')
    else:
        return render(request, 'user_auth/register.html')

def teacher_reg(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        email = request.POST['email']
        username = email  # set username as email
        password = request.POST['password']
        is_staff = True

        # Check if username or email already exists
        if User.objects.filter(username=email).exists() or User.objects.filter(email=email).exists():
            messages.error(request, 'A user with this email already exists.', extra_tags='danger')
            return render(request, 'user_auth/teacher-reg.html')

        # Create the new user
        user = User.objects.create_user(username=username, first_name=first_name, email=email, password=password, is_staff=is_staff)
        # user.save()
        messages.success(request, 'Your account has been created! You can now log in.')
        return render(request, 'user_auth/login.html')
        # print("user created")
        # return redirect('/')
    else:
        return render(request, 'user_auth/teacher-reg.html')



def signin(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = email
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return HttpResponse("<h1>Login Successful</h1>")
        else:
            messages.info(request, 'invalid credentials')
            return render(request, 'user_auth/login.html')
    else:
        return render(request, 'user_auth/login.html')


# def student_signup(request):
#     if request.method == 'POST':
#         first_name = request.POST['first_name']
#         email = request.POST['email']
#         password = request.POST['password']
#
#         user = User.objects.create_user(first_name=first_name, email=email, password=password)
#         user.save()
#         print("user created")
#         return redirect('/')
#     else:
#         return render(request, 'user_auth/student-signup.html')








def signout(request):
    pass

templates/components/nav/navbar.html
{% load static %}
<div class="Header">
        <div class="container">
            <div class="InnerHeader">
                <div routerlink="/" class="Logo" tabindex="0">
                    <img src="{% static 'assets/logo/logo.png' %}" alt="logo">
                </div>
                <div class="Navigation">
                    <div class="Item" tabindex="0">
                        <a class="nav-element" href="index.html"> Home </a>
                    </div>
                    <div class="d-flex">
                        <div class="Item" tabindex="0">
                            <a class="nav-element" href="find-teachers.html"> Find teachers </a>
                        </div>
                    </div>
                    <div class="d-flex">
                        <div class="Item" tabindex="0">
                            <a class="nav-element" href="find-jobs.html"> Find Jobs </a>
                        </div>
                    </div>
                    <div class="Item" tabindex="0">
                        <a class="nav-element" href="resources.html"> Resources </a>
                    </div>
                    <div class="Item" tabindex="0">
                        <a class="nav-element" href="contact.html"> Contact us </a>
                    </div>
                    <div class="Item" tabindex="0">
                        <a class="nav-element" href="faqs.html"> Faqs </a>
                    </div>

                    <div class="Item">
                        <a class="nav-element" href="{% url 'user_auth:signin' %}"> Login </a>
                    </div>
                    <div class="Item">
                        <a class="nav-element" href="{% url 'user_auth:home' %}"> Signup</a>
                    </div>
                </div>
                <div data-toggle="collapse" data-target="#collaspeNavigation" aria-expanded="false"
                    aria-controls="collaspeNavigation" class="HumburgerIcon">
                    <img src="{% static 'assets/icons/header-icon.jpg' %}" alt="icon">
                </div>
            </div>
        </div>
    </div>
    <div class="HamburgerListMenu">
        <div id="collaspeNavigation" class="collapse">
            <div class="Card Card-body">
                <div class="Nav">
                    <div data-toggle="collapse" data-target="#collaspeNavigation" class="Item" tabindex="0">
                        <a class="nav-element" href="index.html"> Home </a>
                    </div>
                    <div class="d-flex">
                        <div data-toggle="collapse" data-target="#collaspeNavigation" class="Item" tabindex="0">
                            <a class="nav-element" href="find-teachers.html"> Find teachers </a>
                        </div>
                    </div>
                    </a>

                    <div class="d-flex">
                        <div data-toggle="collapse" data-target="#collaspeNavigation" class="Item" tabindex="0">
                            <a class="nav-element" href="find-jobs.html"> Find Jobs </a>
                        </div>
                    </div>
                    <div data-toggle="collapse" data-target="#collaspeNavigation" class="Item" tabindex="0">
                        <a class="nav-element" href="resources.html"> Resources </a>
                    </div>
                    <div data-toggle="collapse" data-target="#collaspeNavigation" class="Item" tabindex="0">
                        <a class="nav-element" href="contact.html"> Contact us </a>
                    </div>
                    <div data-toggle="collapse" data-target="#collaspeNavigation" class="Item" tabindex="0">
                        <a class="nav-element" href="faqs.html"> Faqs </a>
                    </div>

                    <div data-toggle="collapse" data-target="#collaspeNavigation" class="Item">
                        <a class="nav-element" href="login.html"> Login </a>
                    </div>
                    <div data-toggle="collapse" data-target="#collaspeNavigation" class="Item">
                        <a class="nav-element" href="signup.html"> Signup</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>

templates/user_auth/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-arp-injected="true">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AlimsOnline – Online Quran Tutor</title>
        <link rel="apple-touch-icon"
              sizes="180x180"
              href="{% static 'assets/favicon/apple-touch-icon.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="32x32"
              href="{% static 'assets/favicon/favicon-32x32.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="16x16"
              href="{% static 'assets/favicon/favicon-16x16.png' %}"/>
        <link rel="manifest" href="{% static 'assets/favicon/site.webmanifest' %}">
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap');

        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300,400,500&display=swap');

        body {
            font-family: 'Raleway', sans-serif;
        }
        </style>
        <link rel="stylesheet"
              href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
              integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/header.css' %}">
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
        <link rel="stylesheet" href="{% static 'css/login.css' %}">
    </head>
    <body class="mat-typography"
          data-new-gr-c-s-check-loaded="14.1102.0"
          data-gr-ext-installed="">

      {% include 'components/nav/navbar.html' %}
      
    <div>
        <div class="CreateAccount">
            <div class="container">
                <div class="MainHeading">
                    <h1 >Create a new account</h1>
                    <!---->
                    <p >
                        Choose an option below to create an
                        account
                    </p>
                    <!----><!----><!---->
                </div>
                <div class="AccountBox">
                    <a href="{% url 'user_auth:register' %}">
                        <div class="Account Student" tabindex="0">
                            <div class="CardDeatils">
                                <img src="{% static 'assets/icons/home-student.png' %}" alt="student"/>
                                <h3>I am a student</h3>
                                <p>Hire teachers for your learning</p>
                            </div>
                        </div>
                    </a>
                    <a href="{% url 'user_auth:teacherReg' %}">
                        <div class="Account Teacher" tabindex="0">
                            <div class="CardDeatils">
                                <img src="{% static 'assets/icons/home-teacher.png' %}" alt="teacher">
                                <h3>I am a teacher</h3>
                                <p>Find teaching jobs</p>
                            </div>
                        </div>
                    </a>
                </div>
                {% comment %} <div class="ChangeOption">
                    <p>You can later change the account type from account settings</p>
                </div> {% endcomment %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</body>
</html>

templates/user_auth/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-arp-injected="true">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AlimsOnline – Online Quran Tutor</title>
        <link rel="apple-touch-icon"
              sizes="180x180"
              href="{% static 'assets/favicon/apple-touch-icon.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="32x32"
              href="{% static 'assets/favicon/favicon-32x32.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="16x16"
              href="{% static 'assets/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'assets/favicon/site.webmanifest' %}">
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap');

        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300,400,500&display=swap');

        body {
            font-family: 'Raleway', sans-serif;
        }
        </style>
        <link rel="stylesheet"
              href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
              integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/header.css' %}">
        <link rel="stylesheet" href="{% static 'css/std-teach-signup.css' %}">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"/>
        <!-- <link rel="stylesheet" href="create-account.css"> -->
    </head>
    <body class="mat-typography"
          data-new-gr-c-s-check-loaded="14.1102.0"
          data-gr-ext-installed="">
      {% include 'components/nav/navbar.html' %}
    <div>
        <div class="CreateAccount">
            <div class="container">
                <div class="MainHeading">
                    <div id="error-message" class="alert alert-danger" style="display:none;"></div>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Error:</strong> {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <h1>Login to your student account</h1>
                    <!--                    <p>Enter  account</p>-->
                </div>
                <form method="POST"  action="{% url 'user_auth:signin' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password"
                               name="password"
                               id="password"
                               class="form-control"
                               required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                </form>
                <div class="DontAccount" tabindex="0">
                    <p>
                        <a href="{% url 'user_auth:home' %}">Don't have an account? Sign Up here</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</body>
</html>

templates/user_auth/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-arp-injected="true">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AlimsOnline – Online Quran Tutor</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'assets/favicon/site.webmanifest' %}">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap');

        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300,400,500&display=swap');

        body {
            font-family: 'Raleway', sans-serif;
        }
    </style>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">

    <link rel="preconnect" href="https://fonts.gstatic.com">


    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/std-teach-signup.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
    <!-- <link rel="stylesheet" href="create-account.css"> -->
</head>


<body class="mat-typography" data-new-gr-c-s-check-loaded="14.1102.0" data-gr-ext-installed="">
        {% include 'components/nav/navbar.html' %}
        <div class="CreateAccount">
            <div class="container">
                <div class="MainHeading">
                <div id="error-message" class="alert alert-danger" style="display:none;"></div>
                    {% if messages %}
                      {% for message in messages %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                          <strong>Error:</strong> {{ message }}
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                      {% endfor %}
                    {% endif %}
                    <h1>Create a new student account</h1>
                    <p>Please fill the form below to create an account</p>

                </div>

                <form method="POST" action="{% url 'user_auth:register' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Name <span class="Red">*</span></label>
                        <input type="text" name="first_name"
                            id="name" placeholder="Name" formcontrolname="name" maxlength="50"
                            class="form-control required">
                    </div>
                    <div class="form-group">
                        <label for="email">Email <span class="Red">*</span></label>
                        <input name = "email"
                            type="email" id="email" aria-describedby="emailHelp" placeholder="Enter email"
                            formcontrolname="email" maxlength="50"
                            class="form-control required">
                    </div>
                    <div class="form-group">
                        <label for="password">Password <span class="Red">*</span></label>
                        <input name="password"
                            type="password" id="password" placeholder="Password" formcontrolname="password"
                            maxlength="50" class="form-control required">
<!--                        <div class="Eye"><i class="fas fa-eye"></i></div>-->
                    </div>
                    <button type="submit" class="btn btn-primary">
                        <span class="ng-star-inserted">Create account</span>
                    </button>
                </form>
                <div class="DontAccount" tabindex="0">
                    <p> <a href="{% url 'user_auth:signin' %}">Already have an account? Sign in here</a> </p>
                </div>
            </div>
        </div>
    </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

</body>

</html>

templates/user_auth/teacher-reg.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-arp-injected="true">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AlimsOnline – Online Quran Tutor</title>
        <link rel="apple-touch-icon"
              sizes="180x180"
              href="{% static 'assets/favicon/apple-touch-icon.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="32x32"
              href="{% static 'assets/favicon/favicon-32x32.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="16x16"
              href="{% static 'assets/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'assets/favicon/site.webmanifest' %}">
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap');

        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300,400,500&display=swap');

        body {
            font-family: 'Raleway', sans-serif;
        }
        </style>
        <link rel="stylesheet"
              href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
              integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/header.css' %}">
        <link rel="stylesheet" href="{% static 'css/std-teach-signup.css' %}">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"/>
        <!-- <link rel="stylesheet" href="create-account.css"> -->
    </head>
    <body class="mat-typography"
          data-new-gr-c-s-check-loaded="14.1102.0"
          data-gr-ext-installed="">
      {% include 'components/nav/navbar.html' %}
        <div>
            <div class="CreateAccount">
                <div class="container">
                    <div class="MainHeading">
                        <h1>Create a new teacher account</h1>
                        <p>Please fill the form below to create an account</p>
                    </div>
                    <form method="POST" action="{% url 'user_auth:teacherReg' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="name">
                                Name <span class="Red">*</span>
                            </label>
                            <input type="text"
                                   name="first_name"
                                   id="name"
                                   placeholder="Name"
                                   formcontrolname="name"
                                   maxlength="50"
                                   class="form-control required">
                        </div>
                        <div class="form-group">
                            <label for="email">
                                Email <span class="Red">*</span>
                            </label>
                            <input name="email"
                                   type="email"
                                   id="email"
                                   aria-describedby="emailHelp"
                                   placeholder="Enter email"
                                   formcontrolname="email"
                                   maxlength="50"
                                   class="form-control required">
                        </div>
                        <div class="form-group">
                            <label for="password">
                                Password <span class="Red">*</span>
                            </label>
                            <input name="password"
                                   type="password"
                                   id="password"
                                   placeholder="Password"
                                   formcontrolname="password"
                                   maxlength="50"
                                   class="form-control required">
                            <!--                        <div class="Eye"><i class="fas fa-eye"></i></div>-->
                        </div>
                        <button type="submit" class="btn btn-primary">
                            <span class="ng-star-inserted">Create account</span>
                        </button>
                    </form>
                    <div class="DontAccount" tabindex="0">
                        <p>
                            <a href="{% url 'user_auth:signin' %}">Already have an account? Sign in here</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"></script>
    </body>
</html>